#!/bin/bash

LIMIT=30
GH_USER=

usage() {
    echo "$(basename $0): quickly clone git repositories with fzf search"
    echo "Usage: $(basename $0) [-l <positive int>] [-u user/organization]"
    echo " -l: limit is the maximum number of git repositories to load; defaults to $LIMIT."
    echo " -u: the git user or organization to search for repos under (ex: -u torvalds)"
    echo ""
    echo "NOTE: To quickly move this script to the correct location so that this "
    echo "this script be available for use globally, run $ $(basename $0) init"
    exit 0
}

# just a quick way to move the script to the right place
if [ $# -ge 1 ] && [ $1 = "init" ]; then
    read -p "Move $(basename "$0") to /usr/local/bin/?" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
        sudo mv $SCRIPT_DIR/$(basename "$0") /usr/local/bin/
    fi
    exit 0
fi

while getopts ":l:u:h" o; do
    case "${o}" in
        l)
            LIMIT=${OPTARG}
            (($LIMIT > 0)) || usage
            ;;
        u)
            GH_USER=${OPTARG}
            ;;
        h)
            usage
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# test that limit is a number
re='^[0-9]+$'
if ! [[ $LIMIT =~ $re ]]; then
   echo "error: limit not a number" >&2
   exit 1
fi

# get repos, fet just the names, open fzf and take output
REPO_NAME=$((gh repo list $GH_USER -L $LIMIT | cut -f1 -d$'\t') | fzf);

# verify selection wasn't empty
if [ "$REPO_NAME" = "" ]; then
    exit 1
fi

# clone it
REPO=git@github.com:$REPO_NAME.git
git clone $REPO


