#!/bin/bash

set -Eeuo pipefail

LIMIT=30
GH_USER=
SEARCH=""
do_search=0
do_user_org_search=0

usage() {
    echo "$(basename $0): quickly clone git repositories with fzf search"
    echo "Usage: $(basename $0) [-l <positive int>] [-u <user or organization string>] [-s <string>]"
    echo " -l: limit is the maximum number of git repositories to load; defaults to $LIMIT."
    echo " -u: changes the git user or organization to search for repos under (ex: -u torvalds); defaults to your account"
    echo " -s: if specified, instead of searching by user/organization, searches for repos that match the query string"
    echo ""
    echo "NOTE: To quickly move this script to the correct location so that this "
    echo "this script be available for use globally, run $ $(basename $0) init"
    exit 0
}

# just a quick way to move the script to the right place
if [ $# -ge 1 ] && [ $1 = "init" ]; then
    read -p "Move $(basename "$0") to /usr/local/bin/?" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
        sudo mv $SCRIPT_DIR/$(basename "$0") /usr/local/bin/
    fi
    exit 0
fi

while getopts ":l:u:s:h" o; do
    case "${o}" in
        l)
            LIMIT=${OPTARG}
            (($LIMIT > 0)) || usage
            ;;
        u)
            GH_USER=${OPTARG}
            do_user_org_search=1
            ;;
        s)
            SEARCH=${OPTARG}
            do_search=1
            ;;
        h)
            usage
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ $do_user_org_search = 1 ] && [ $do_search = 1 ]; then
    usage;
fi

if [ $do_search = 1 ]; then
    REPO_NAME=$((gh search repos $SEARCH -L $LIMIT | cut -f1 -d$'\t') | fzf);
else
    # get repos, fet just the names, open fzf and take output
    REPO_NAME=$((gh repo list $GH_USER -L $LIMIT | cut -f1 -d$'\t') | fzf);
fi

# verify selection wasn't empty
if [ "$REPO_NAME" = "" ]; then
    exit 1
fi

# clone it
REPO=git@github.com:$REPO_NAME.git
git clone $REPO


